# Generated by Django 6.0.2 on 2026-02-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True, verbose_name='Order Number')),
                ('title', models.CharField(max_length=255, verbose_name='Step name')),
                ('message_text', models.TextField(verbose_name='Text message')),
                ('url', models.URLField(max_length=500, verbose_name='Video Link')),
                ('delay_minutes', models.PositiveIntegerField(default=0, verbose_name='Задержка отправки (в минутах)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video Plural',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('tg_id', models.BigIntegerField(blank=True, null=True)),
                ('vk_id', models.BigIntegerField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_on_step', to='app.videolink', verbose_name='Current step')),
            ],
            options={
                'verbose_name': '=User=',
                'verbose_name_plural': 'User Plural',
                'indexes': [models.Index(fields=['tg_id'], name='app_user_tg_id_30f61c_idx'), models.Index(fields=['vk_id'], name='app_user_vk_id_44cdb1_idx')],
            },
        ),
    ]
