TEXTS = {
    "text_welcome": "Добро пожаловать! Рад тебя видеть. 👇 Вот доступные материалы:",
    "btn_start": "Старт",
    "text_no_links": "На данный момент материалов нет, загляните позже!",
    "text_removed_link": "✅ Удалено",
    "text_error_removed": "❌ Ошибка удаления",
    "text_restrict_admin": "⛔️ У вас нет прав администратора.",
    "text_admin_panel": "🔧 Панель администратора:",
    "text_welcome_admin": "👨‍💻 Вы опознаны как администратор.\nВведите /admin для входа в панель управления.",
    "text_admin_article": "Отправьте сообщение (текст, фото, видео, голосовое) для всех.\n\n",
    "text_start_mailing": "Начинаю рассылку ...",
    "text_finish_mailing": "Рассылка завершена. Успешно отправлено:",
    "text_title_step": "Введите название шага (Title):",
    "text_description_step": "Введите текст описания:",
    "text_link_step": "Введите адрес ссылки:",
    "text_wrong_link": "❌ Ссылка должна начинаться с http. Попробуйте снова.",
    "text_link_added": "✅ Ссылка добавлена! Номер шага:",
    "text_empty_list": "Список пуст",
    "text_btn_remove": "Нажмите на пункт, чтобы УДАЛИТЬ его:",
    "text_btn_art": "Написать анонс",
    "text_btn_link": "➕ Добавить ссылку",
    "text_btn_rem": "📋 Список (Удалить)",
    "text_btn_next": "Далее ⏩",
    "text_btn_back": "🔙 Назад",
}
